name: "Move Tests"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  intent-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./intent-framework
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Runs move tests.
        run: nix-shell --command 'aptos move test --dev'